#i2s
ARECORD = "arecord"
APLAY = "aplay"

CAPTURE_DEVICE = "plughw:1,0"
PLAYBACK_DEVICE = "plughw:0,0"

AUDIO_RATE = 48000
AUDIO_CHANNELS = 1
AUDIO_FORMAT = "S32_LE"

AUDIO_BUFFER_SIZE = 8192   # or 16384
AUDIO_PERIOD_SIZE = 2048   # or 4096

AUDIO_TERMINATE_TIMEOUT = 2


# SPI

SPI_PORT = 0
SPI_DEVICE = 0
SPI_BUS_SPEED = 16_000_000

# Display

DISPLAY_WIDTH = 160
DISPLAY_HEIGHT = 128

DISPLAY_ROTATION = 1
DISPLAY_H_OFFSET = 1
DISPLAY_V_OFFSET = 2

GPIO_DISPLAY_DC = 17
GPIO_DISPLAY_RST = 25
GPIO_DISPLAY_BL = 22


# Display fonts
DISPLAY_FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
DISPLAY_TITLE_SIZE = 20
DISPLAY_SUBTITLE_SIZE = 12

# Text positions
DISPLAY_TITLE_Y = 30
DISPLAY_SUBTITLE_Y = 58
DISPLAY_MARGIN_X = 10

COLOR_BACKGROUND = "black"
COLOR_TITLE = "white"
COLOR_SUBTITLE = "white"


GPIO_BUTTON = 26

BUTTON_POLL_INTERVAL = 0.005      # 5 ms
BUTTON_DEBOUNCE_TIME = 0.03        # 30 ms